spring:
  datasource:
    url: jdbc:mysql://10.11.24.154:3306/dataclean?useOldAliasMetadataBehavior=true
    #url: jdbc:mysql://10.11.24.169:3306/dataclean?useOldAliasMetadataBehavior=true
    username: root
    password: Hdu@123456
    #password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8181


